apiVersion: rds.aws.m.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/dbinstanceautomatedbackupsreplication
  labels:
    testing.upbound.io/example-name: default-test
  name: default-dbiabr
  namespace: upbound-system
spec:
  forProvider:
    allocatedStorage: 10
    autoGeneratePassword: true
    backupRetentionPeriod: 7
    dbName: mydb
    engine: mysql
    engineVersion: "5.7"
    instanceClass: db.t3.micro
    parameterGroupName: default.mysql5.7
    passwordSecretRef:
      key: password
      name: example-dbinstance
    region: us-west-1
    skipFinalSnapshot: true
    username: foo
  writeConnectionSecretToRef:
    name: example-dbinstance-out
  providerConfigRef:
    name: default