apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-with-crossplane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rafaelhueb92/EKS-with-Crossplane
    targetRevision: main
    path: 03-argocd/manifests/.
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: 
      selfHeal: true
